// GENERATED by endgame2/AGENTS/Tasks/20261001_090718_LetterTraining/scripts/gen_train_ts.py - do not edit by hand.
// ARCHIVE MODEL (Phase C, `_LetterTraining_PROMPTS.md` / "## Follow-up prompt 9 — mobile-apps-preferences"): the train
// pictures are backend-served from `train/train.zip`; `file` is the entry name inside that archive (app/train.tsx maps
// it to a data URI). EN letter audio stays bundled (letter audio = bundled, user decision 2). Transformed by endgame2
// AGENTS/Tasks/20261001_162724_LetterTrainingMobileAppsPreferences/scripts/transform_asset_maps_to_archives.js.
// Train geometry (assets/train/manifest.json, fractions of the image size) + English letter audio for "Abecedový vlak" -
// `_LetterTraining_PROMPTS.md` / "## Follow-up prompt 5 — new game "Abecedový vlak" (verbatim)", "## Q&A 6", "## Q&A 7".
// Empty lists = images not generated yet: the game draws placeholder engines/wagons.

import { TrainImage, WagonImage } from './types';

export const ENGINE_IMAGES: readonly TrainImage[] = [
  { file: 'engines/engine01.png', aspect: 1.5944, baseline: 1.0 },
  { file: 'engines/engine02.png', aspect: 1.9194, baseline: 1.0 },
  { file: 'engines/engine03.png', aspect: 2.3861, baseline: 1.0 },
  { file: 'engines/engine04.png', aspect: 2.0611, baseline: 1.0 },
  { file: 'engines/engine05.png', aspect: 1.8167, baseline: 1.0 },
  { file: 'engines/engine06.png', aspect: 1.6194, baseline: 1.0 },
  { file: 'engines/engine07.png', aspect: 1.7056, baseline: 1.0 },
  { file: 'engines/engine08.png', aspect: 2.3417, baseline: 1.0 },
  { file: 'engines/engine09.png', aspect: 1.5889, baseline: 1.0 },
  { file: 'engines/engine10.png', aspect: 1.7639, baseline: 1.0 },
];

export const WAGON_IMAGES: readonly WagonImage[] = [
  { file: 'wagons/wagon01.png', aspect: 1.4867, baseline: 1.0, panel: { x: 0.278, y: 0.3567, width: 0.5, height: 0.34 } },
  { file: 'wagons/wagon02.png', aspect: 1.56, baseline: 1.0, panel: { x: 0.2479, y: 0.3467, width: 0.5385, height: 0.3367 } },
  { file: 'wagons/wagon03.png', aspect: 1.73, baseline: 1.0, panel: { x: 0.2119, y: 0.21, width: 0.6166, height: 0.4 } },
  { file: 'wagons/wagon04.png', aspect: 1.64, baseline: 1.0, panel: { x: 0.2825, y: 0.3233, width: 0.437, height: 0.36 } },
  { file: 'wagons/wagon05.png', aspect: 1.5767, baseline: 1.0, panel: { x: 0.2178, y: 0.3233, width: 0.5751, height: 0.3467 } },
  { file: 'wagons/wagon06.png', aspect: 1.32, baseline: 1.0, panel: { x: 0.2172, y: 0.4, width: 0.5758, height: 0.3167 } },
  { file: 'wagons/wagon07.png', aspect: 1.3233, baseline: 1.0, panel: { x: 0.2267, y: 0.3167, width: 0.5693, height: 0.36 } },
  { file: 'wagons/wagon08.png', aspect: 1.4067, baseline: 1.0, panel: { x: 0.2583, y: 0.3767, width: 0.4858, height: 0.3133 } },
  { file: 'wagons/wagon09.png', aspect: 1.33, baseline: 1.0, panel: { x: 0.2055, y: 0.4167, width: 0.5915, height: 0.3233 } },
  { file: 'wagons/wagon10.png', aspect: 1.7333, baseline: 1.0, panel: { x: 0.2692, y: 0.3, width: 0.4731, height: 0.4033 } },
];

export const EN_LETTER_AUDIO: Readonly<Record<string, number>> = {
  'a': require('../../assets/audio/letters_en/a.mp3'),
  'b': require('../../assets/audio/letters_en/b.mp3'),
  'c': require('../../assets/audio/letters_en/c.mp3'),
  'd': require('../../assets/audio/letters_en/d.mp3'),
  'e': require('../../assets/audio/letters_en/e.mp3'),
  'f': require('../../assets/audio/letters_en/f.mp3'),
  'g': require('../../assets/audio/letters_en/g.mp3'),
  'h': require('../../assets/audio/letters_en/h.mp3'),
  'i': require('../../assets/audio/letters_en/i.mp3'),
  'j': require('../../assets/audio/letters_en/j.mp3'),
  'k': require('../../assets/audio/letters_en/k.mp3'),
  'l': require('../../assets/audio/letters_en/l.mp3'),
  'm': require('../../assets/audio/letters_en/m.mp3'),
  'n': require('../../assets/audio/letters_en/n.mp3'),
  'o': require('../../assets/audio/letters_en/o.mp3'),
  'p': require('../../assets/audio/letters_en/p.mp3'),
  'q': require('../../assets/audio/letters_en/q.mp3'),
  'r': require('../../assets/audio/letters_en/r.mp3'),
  's': require('../../assets/audio/letters_en/s.mp3'),
  't': require('../../assets/audio/letters_en/t.mp3'),
  'u': require('../../assets/audio/letters_en/u.mp3'),
  'v': require('../../assets/audio/letters_en/v.mp3'),
  'w': require('../../assets/audio/letters_en/w.mp3'),
  'x': require('../../assets/audio/letters_en/x.mp3'),
  'y': require('../../assets/audio/letters_en/y.mp3'),
  'z': require('../../assets/audio/letters_en/z.mp3'),
};
