// App-specific glue of the pexeso (the ONLY pexeso file that differs between LetterTraining and LetterPexeso; every other
// pexeso file is kept identical). LetterPexeso variant: generated src/pexesoWords.ts (Level-1-eligible words copied from
// LetterTraining by endgame2 AGENTS/Tasks/20261001_090718_LetterTraining/scripts/pexeso/gen_pexeso_words.py) -
// `_LetterPexeso_PROMPTS.md` / "Q&A 9 — Pexeso improvements round 2" (standalone: full feature set).
// Archive model (`_LetterPexeso_PROMPTS.md` / "## Phase E — mobile-apps-preferences in the standalone app"; decisions
// recorded in LetterTraining's `_LetterTraining_PROMPTS.md` / "## Follow-up prompt 9 — mobile-apps-preferences"): word
// pictures/audio are backend-served (words/<id>.zip); only letter audio, the ear picture and the downsized settings
// samples stay bundled.

export { enablePlaybackInSilentMode, playAudio, stopAllAudio, stopAudioIfOwnedBy } from './audioController';
export { PEXESO_LETTER_AUDIO, PEXESO_WORDS } from './pexesoWords';
// Backend-resource access for the shared pexeso files (they must not import resources/ directly: the relative path
// differs between the two apps, so the glue re-exports it).
export { OfflineRetry } from './resources/OfflineRetry';
export { useArchivePreloading } from './resources/useArchivePreloading';
// Shared themed start animation (Phase D) — same relative-path reason as above.
export { StartAnimation } from './startAnimation/StartAnimation';
export type { UnpackedArchive } from './resources/types';

// One identical ear-with-sound picture on every sound card - "Q&A 9 — Pexeso improvements round 2".
export const EAR_IMAGE: number = require('../assets/pexeso_ear.png');

// A few BUNDLED, DOWNSIZED (168 px — the preview renders at 56 px logical, i.e. 168 px @3x) sample pictures for the
// settings preview of the "Obrázky" card type — user decision 9 ("bundled samples for settings; backend for boards").
// Byte-identical copies of LetterTraining/assets/images/pexeso_samples (generated by endgame2
// AGENTS/Tasks/20261001_162724_LetterTrainingMobileAppsPreferences/scripts/make_pexeso_samples.ps1).
export const PEXESO_SAMPLE_IMAGES: readonly number[] = [
  require('../assets/images/pexeso_samples/auto.png'),
  require('../assets/images/pexeso_samples/kocka.png'),
  require('../assets/images/pexeso_samples/balon.png'),
];
