// App-specific glue of the pexeso (the ONLY pexeso file that differs between LetterTraining and LetterPexeso; every
// other pexeso file is kept identical — restored by the Phase E sync of the archive model to the standalone app).
// LetterTraining variant: words + letter audio from the generated src/words.ts.
// Image cards use Level-1-eligible words only - `_LetterPexeso_PROMPTS.md` / "Follow-up prompt 6 — Pexeso improvements
// (standalone LetterPexeso + integrated in LetterTraining) (verbatim)" + "Q&A 8 — Pexeso improvements round 1".
// Archive model (`_LetterTraining_PROMPTS.md` / "## Follow-up prompt 9 — mobile-apps-preferences"): word pictures/audio
// are backend-served (words/<id>.zip); only letter audio, the ear picture and the downsized settings samples stay bundled.

import type { LetterAudioMap } from '../wordStarts/types';
import { LETTER_AUDIO, WORDS } from '../words';
import type { PexesoWord } from './game/pexesoLogic';

export { playAudio, stopAllAudio, stopAudioIfOwnedBy } from '../audioController';
// Backend-resource access for the shared pexeso files (they must not import ../resources directly: the relative path
// differs in the standalone LetterPexeso app, so the glue re-exports it).
export { OfflineRetry } from '../resources/OfflineRetry';
export { useArchivePreloading } from '../resources/useArchivePreloading';
// Shared themed start animation (Phase D) — same relative-path reason as above.
export { StartAnimation } from '../startAnimation/StartAnimation';
export type { UnpackedArchive } from '../resources/types';

export const PEXESO_WORDS: readonly PexesoWord[] = WORDS.filter((entry) => !entry.excludeLevel1).map((entry) => ({
  id: entry.id,
  word: entry.word,
  firstLetter: entry.firstLetter,
  archivePath: `words/${entry.id}.zip`,
}));

// Pexeso keeps DISTINGUISHING vowel readings, unlike the general long-vowel LETTER_AUDIO (A "á" long, Á "dlouhé á",
// I "měkké í", í "dlouhé měkké í", E/O/U "é/ó/ú" long, ú/ů named) - `_LetterTraining_PROMPTS.md` /
// "## Follow-up prompt 11" + "## Q&A 11" + "## Follow-up prompt 16 — Long vowel pronunciation everywhere".
export const PEXESO_LETTER_AUDIO: LetterAudioMap = {
  ...LETTER_AUDIO,
  'a': require('../../assets/audio/letters/a_long.mp3'),
  'á': require('../../assets/audio/letters/aa.mp3'),
  'e': require('../../assets/audio/letters/e_long.mp3'),
  'é': require('../../assets/audio/letters/ee.mp3'),
  'i': require('../../assets/audio/letters/i_soft_long.mp3'),
  'í': require('../../assets/audio/letters/ii.mp3'),
  'o': require('../../assets/audio/letters/o_long.mp3'),
  'ó': require('../../assets/audio/letters/oo.mp3'),
  'u': require('../../assets/audio/letters/u_long.mp3'),
  'ú': require('../../assets/audio/letters/uu.mp3'),
  'ů': require('../../assets/audio/letters/uo.mp3'),
};

// One identical ear-with-sound picture on every sound card - "Q&A 9 — Pexeso improvements round 2".
export const EAR_IMAGE: number = require('../../assets/images/pexeso_ear.png');

// A few BUNDLED, DOWNSIZED (168 px — the preview renders at 56 px logical, i.e. 168 px @3x; verification Phase C R1
// L5) sample pictures for the settings preview of the "Obrázky" card type —
// user decision 9 ("bundled samples for settings; backend for boards", samples "converted to smaller sized pictures").
// Generated by endgame2 AGENTS/Tasks/20261001_162724_LetterTrainingMobileAppsPreferences/scripts/make_pexeso_samples.ps1.
export const PEXESO_SAMPLE_IMAGES: readonly number[] = [
  require('../../assets/images/pexeso_samples/auto.png'),
  require('../../assets/images/pexeso_samples/kocka.png'),
  require('../../assets/images/pexeso_samples/balon.png'),
];
