// App-specific glue of the pexeso (the one pexeso file INTENDED to differ between LetterTraining and LetterPexeso;
// the other pexeso files are meant to be kept identical — TEMPORARILY UNTRUE: PexesoGame.tsx, components/PexesoCard.tsx,
// game/pexesoLogic.ts and PexesoSettingsScreen.tsx carry the archive model here and await the Phase E sync to the
// standalone LetterPexeso). LetterTraining variant: words + letter audio from the generated src/words.ts.
// Image cards use Level-1-eligible words only - `_LetterPexeso_PROMPTS.md` / "Follow-up prompt 6 — Pexeso improvements
// (standalone LetterPexeso + integrated in LetterTraining) (verbatim)" + "Q&A 8 — Pexeso improvements round 1".
// Archive model (`_LetterTraining_PROMPTS.md` / "## Follow-up prompt 9 — mobile-apps-preferences"): word pictures/audio
// are backend-served (words/<id>.zip); only letter audio, the ear picture and the downsized settings samples stay bundled.

import type { LetterAudioMap } from '../wordStarts/types';
import { LETTER_AUDIO, WORDS } from '../words';
import type { PexesoWord } from './game/pexesoLogic';

export { playAudio, stopAllAudio, stopAudioIfOwnedBy } from '../audioController';
// Backend-resource access for the shared pexeso files (they must not import ../resources directly: the relative path
// differs in the standalone LetterPexeso app, so the glue re-exports it).
export { OfflineRetry } from '../resources/OfflineRetry';
export { useArchivePreloading } from '../resources/useArchivePreloading';
export type { UnpackedArchive } from '../resources/types';

export const PEXESO_WORDS: readonly PexesoWord[] = WORDS.filter((entry) => !entry.excludeLevel1).map((entry) => ({
  id: entry.id,
  word: entry.word,
  firstLetter: entry.firstLetter,
  archivePath: `words/${entry.id}.zip`,
}));

export const PEXESO_LETTER_AUDIO: LetterAudioMap = LETTER_AUDIO;

// One identical ear-with-sound picture on every sound card - "Q&A 9 — Pexeso improvements round 2".
export const EAR_IMAGE: number = require('../../assets/images/pexeso_ear.png');

// A few BUNDLED, DOWNSIZED (168 px — the preview renders at 56 px logical, i.e. 168 px @3x; verification Phase C R1
// L5) sample pictures for the settings preview of the "Obrázky" card type —
// user decision 9 ("bundled samples for settings; backend for boards", samples "converted to smaller sized pictures").
// Generated by endgame2 AGENTS/Tasks/20261001_162724_LetterTrainingMobileAppsPreferences/scripts/make_pexeso_samples.ps1.
export const PEXESO_SAMPLE_IMAGES: readonly number[] = [
  require('../../assets/images/pexeso_samples/auto.png'),
  require('../../assets/images/pexeso_samples/kocka.png'),
  require('../../assets/images/pexeso_samples/balon.png'),
];
