// Data model for the comprehension game — fields 5.1/5.2/5.3 structure.
// Requested in _TreninkPorozumeni_Fields123_PROMPTS.md (section "User request") and detailed
// in _TreninkPorozumeni_SPEC.md (sections "Fields" and "Examples").
// Wrong-answer spoken explanations requested in _TreninkPorozumeni_Fields123_PROMPTS.md
// (section "User follow-up request — spoken explanation of a wrong picture").
// Asset naming contract per example id:
//   audio:  assets/audio/<id>.mp3
//   images: assets/images/<id>_target.png, <id>_gram.png, <id>_lexa.png, <id>_lexb.png
//   explanation audio: assets/audio/<id>_gram_why.mp3, <id>_lexa_why.mp3, <id>_lexb_why.mp3

import { AudioSource } from 'expo-audio';
import { ImageSourcePropType } from 'react-native';

export type FieldId = 'field51' | 'field52' | 'field53';

export interface ComprehensionExample {
  id: string; // unique slug
  field: FieldId;
  sentence: string; // Czech sentence played/shown
  audio: AudioSource; // assets/audio/<id>.mp3
  targetImage: ImageSourcePropType; // assets/images/<id>_target.png
  grammaticalDistractorImage: ImageSourcePropType; // assets/images/<id>_gram.png
  lexicalDistractorAImage: ImageSourcePropType; // assets/images/<id>_lexa.png
  lexicalDistractorBImage: ImageSourcePropType; // assets/images/<id>_lexb.png
  // Why-it-is-wrong explanations (5-20 words, simple child-friendly Czech), spoken when
  // the given distractor is tapped. If an audio file is ever missing (null), the game
  // falls back to the plain 500 ms red tint.
  grammaticalDistractorExplanation: string;
  grammaticalDistractorExplanationAudio: AudioSource | null; // assets/audio/<id>_gram_why.mp3
  lexicalDistractorAExplanation: string;
  lexicalDistractorAExplanationAudio: AudioSource | null; // assets/audio/<id>_lexa_why.mp3
  lexicalDistractorBExplanation: string;
  lexicalDistractorBExplanationAudio: AudioSource | null; // assets/audio/<id>_lexb_why.mp3
}

// Sentences, picture contents, and explanation texts follow the content spec
// (AGENTS/Tasks/20260930_135545_TreninkPorozumeniFields123/content_spec.md in the
// endgame repository), sections "Reused legacy items" and "New 5.1 items".
// Migrated from the original two-image data model (see git history of this file):
// the old items had sentenceA/sentenceB + imageA/imageB role-swapped pairs. Here each
// old item becomes ONE field-5.1 example: sentence = old sentenceA, audio = old <id>_a.mp3,
// target = old <id>_a.png, grammatical distractor = old <id>_b.png (the role-swapped scene).
// The grammatical explanations below describe the role-swapped scene (old sentenceB semantics):
// "Tady <swapped roles>, ne <correct roles>."
// The old `kosa` item („Jel s kosou." / „Jel s kozou.") is intentionally EXCLUDED:
// it is a phonological minimal pair (kosa/koza), not a reversible sentence, so it does
// not belong to field 5.1. It is kept aside for a future phonological field; its assets
// remain in assets/audio and assets/images.
export const comprehensionExamples: ComprehensionExample[] = [
  {
    id: 'honi',
    field: 'field51',
    sentence: 'Bratr honí sestru.',
    audio: require('../assets/audio/honi_a.mp3'),
    targetImage: require('../assets/images/honi_a.png'),
    grammaticalDistractorImage: require('../assets/images/honi_b.png'),
    lexicalDistractorAImage: require('../assets/images/honi_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/honi_lexb.png'),
    grammaticalDistractorExplanation: 'Tady honí sestra bratra, ne bratr sestru.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/honi_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady kluk honí pejska, ne sestru.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/honi_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady honí maminka, ne bratr.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/honi_lexb_why.mp3'),
  },
  {
    id: 'tlaci',
    field: 'field51',
    sentence: 'Medvěd tlačí lva.',
    audio: require('../assets/audio/tlaci_a.mp3'),
    targetImage: require('../assets/images/tlaci_a.png'),
    grammaticalDistractorImage: require('../assets/images/tlaci_b.png'),
    lexicalDistractorAImage: require('../assets/images/tlaci_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/tlaci_lexb.png'),
    grammaticalDistractorExplanation: 'Tady tlačí lev medvěda, ne medvěd lva.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/tlaci_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady medvěd tlačí vlka, ne lva.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/tlaci_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady tlačí králík, ne medvěd.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/tlaci_lexb_why.mp3'),
  },
  {
    id: 'vysetruje',
    field: 'field51',
    sentence: 'Doktor vyšetřuje pacienta.',
    audio: require('../assets/audio/vysetruje_a.mp3'),
    targetImage: require('../assets/images/vysetruje_a.png'),
    grammaticalDistractorImage: require('../assets/images/vysetruje_b.png'),
    lexicalDistractorAImage: require('../assets/images/vysetruje_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/vysetruje_lexb.png'),
    grammaticalDistractorExplanation: 'Tady vyšetřuje pacient doktora, ne doktor pacienta.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/vysetruje_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady doktor vyšetřuje medvídka, ne pacienta.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/vysetruje_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady vyšetřuje sestřička, ne doktor.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/vysetruje_lexb_why.mp3'),
  },
  {
    id: 'cese',
    field: 'field51',
    sentence: 'Holčička češe maminku.',
    audio: require('../assets/audio/cese_a.mp3'),
    targetImage: require('../assets/images/cese_a.png'),
    grammaticalDistractorImage: require('../assets/images/cese_b.png'),
    lexicalDistractorAImage: require('../assets/images/cese_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/cese_lexb.png'),
    grammaticalDistractorExplanation: 'Tady češe maminka holčičku, ne holčička maminku.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/cese_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady holčička češe panenku, ne maminku.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/cese_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady češe kluk, ne holčička.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/cese_lexb_why.mp3'),
  },
  {
    id: 'preskakuje',
    field: 'field51',
    sentence: 'Kůň přeskakuje krávu.',
    audio: require('../assets/audio/preskakuje_a.mp3'),
    targetImage: require('../assets/images/preskakuje_a.png'),
    grammaticalDistractorImage: require('../assets/images/preskakuje_b.png'),
    lexicalDistractorAImage: require('../assets/images/preskakuje_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/preskakuje_lexb.png'),
    grammaticalDistractorExplanation: 'Tady skáče kráva přes koně, ne kůň přes krávu.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/preskakuje_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady kůň přeskakuje plot, ne krávu.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/preskakuje_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady skáče pes, ne kůň.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/preskakuje_lexb_why.mp3'),
  },
  {
    id: 'fotografuje',
    field: 'field51',
    sentence: 'Kluk fotografuje dědečka.',
    audio: require('../assets/audio/fotografuje_a.mp3'),
    targetImage: require('../assets/images/fotografuje_a.png'),
    grammaticalDistractorImage: require('../assets/images/fotografuje_b.png'),
    lexicalDistractorAImage: require('../assets/images/fotografuje_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/fotografuje_lexb.png'),
    grammaticalDistractorExplanation: 'Tady fotografuje dědeček kluka, ne kluk dědečka.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/fotografuje_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady kluk fotografuje babičku, ne dědečka.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/fotografuje_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady kluk dědečka maluje, nefotografuje ho.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/fotografuje_lexb_why.mp3'),
  },
  {
    id: 'skrabe',
    field: 'field51',
    sentence: 'Kočka škrábe psa.',
    audio: require('../assets/audio/skrabe_a.mp3'),
    targetImage: require('../assets/images/skrabe_a.png'),
    grammaticalDistractorImage: require('../assets/images/skrabe_b.png'),
    lexicalDistractorAImage: require('../assets/images/skrabe_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/skrabe_lexb.png'),
    grammaticalDistractorExplanation: 'Tady škrábe pes kočku, ne kočka psa.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/skrabe_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady kočka škrábe strom, ne psa.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/skrabe_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady škrábe liška, ne kočka.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/skrabe_lexb_why.mp3'),
  },
  {
    id: 'vede',
    field: 'field51',
    sentence: 'Policista vede zloděje.',
    audio: require('../assets/audio/vede_a.mp3'),
    targetImage: require('../assets/images/vede_a.png'),
    grammaticalDistractorImage: require('../assets/images/vede_b.png'),
    lexicalDistractorAImage: require('../assets/images/vede_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/vede_lexb.png'),
    grammaticalDistractorExplanation: 'Tady vede zloděj policistu, ne policista zloděje.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/vede_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady policista vede pejska, ne zloděje.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/vede_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady vede hasič, ne policista.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/vede_lexb_why.mp3'),
  },
  {
    id: 'zachranuje',
    field: 'field51',
    sentence: 'Princ zachraňuje princeznu.',
    audio: require('../assets/audio/zachranuje_a.mp3'),
    targetImage: require('../assets/images/zachranuje_a.png'),
    grammaticalDistractorImage: require('../assets/images/zachranuje_b.png'),
    lexicalDistractorAImage: require('../assets/images/zachranuje_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/zachranuje_lexb.png'),
    grammaticalDistractorExplanation: 'Tady zachraňuje princezna prince, ne princ princeznu.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/zachranuje_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady princ zachraňuje kluka, ne princeznu.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/zachranuje_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady zachraňuje hasič, ne princ.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/zachranuje_lexb_why.mp3'),
  },
  {
    id: 'chvali',
    field: 'field51',
    sentence: 'Učitel chválí žáka.',
    audio: require('../assets/audio/chvali_a.mp3'),
    targetImage: require('../assets/images/chvali_a.png'),
    grammaticalDistractorImage: require('../assets/images/chvali_b.png'),
    lexicalDistractorAImage: require('../assets/images/chvali_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/chvali_lexb.png'),
    grammaticalDistractorExplanation: 'Tady chválí žák učitele, ne učitel žáka.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/chvali_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady chválí maminka, ne učitel.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/chvali_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady se učitel zlobí, žáka nechválí.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/chvali_lexb_why.mp3'),
  },
  // New 5.1 items (content spec items 11-20) — all four pictures newly generated.
  {
    id: 'strika',
    field: 'field51',
    sentence: 'Na kluka stříká holčička.',
    audio: require('../assets/audio/strika.mp3'),
    targetImage: require('../assets/images/strika_target.png'),
    grammaticalDistractorImage: require('../assets/images/strika_gram.png'),
    lexicalDistractorAImage: require('../assets/images/strika_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/strika_lexb.png'),
    grammaticalDistractorExplanation: 'Tady stříká kluk na holčičku, ne holčička na kluka.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/strika_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady holčička stříká na pejska, ne na kluka.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/strika_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady stříká maminka, ne holčička.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/strika_lexb_why.mp3'),
  },
  {
    id: 'kouse',
    field: 'field51',
    sentence: 'Koně kouše pes.',
    audio: require('../assets/audio/kouse.mp3'),
    targetImage: require('../assets/images/kouse_target.png'),
    grammaticalDistractorImage: require('../assets/images/kouse_gram.png'),
    lexicalDistractorAImage: require('../assets/images/kouse_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/kouse_lexb.png'),
    grammaticalDistractorExplanation: 'Tady kouše kůň psa, ne pes koně.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/kouse_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady pes kouše krávu, ne koně.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/kouse_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady kouše vlk, ne pes.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/kouse_lexb_why.mp3'),
  },
  {
    id: 'veze',
    field: 'field51',
    sentence: 'Kluka veze holčička na sáňkách.',
    audio: require('../assets/audio/veze.mp3'),
    targetImage: require('../assets/images/veze_target.png'),
    grammaticalDistractorImage: require('../assets/images/veze_gram.png'),
    lexicalDistractorAImage: require('../assets/images/veze_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/veze_lexb.png'),
    grammaticalDistractorExplanation: 'Tady veze kluk holčičku, ne holčička kluka.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/veze_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady holčička veze medvídka, ne kluka.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/veze_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady veze maminka, ne holčička.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/veze_lexb_why.mp3'),
  },
  {
    id: 'tlacimotorku',
    field: 'field51',
    sentence: 'Motorku tlačí auto.',
    audio: require('../assets/audio/tlacimotorku.mp3'),
    targetImage: require('../assets/images/tlacimotorku_target.png'),
    grammaticalDistractorImage: require('../assets/images/tlacimotorku_gram.png'),
    lexicalDistractorAImage: require('../assets/images/tlacimotorku_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/tlacimotorku_lexb.png'),
    grammaticalDistractorExplanation: 'Tady tlačí motorka auto, ne auto motorku.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/tlacimotorku_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady tlačí traktor, ne auto.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/tlacimotorku_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady auto tlačí kolo, ne motorku.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/tlacimotorku_lexb_why.mp3'),
  },
  {
    id: 'objima',
    field: 'field51',
    sentence: 'Babičku objímá holčička.',
    audio: require('../assets/audio/objima.mp3'),
    targetImage: require('../assets/images/objima_target.png'),
    grammaticalDistractorImage: require('../assets/images/objima_gram.png'),
    lexicalDistractorAImage: require('../assets/images/objima_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/objima_lexb.png'),
    grammaticalDistractorExplanation: 'Tady objímá babička holčičku, ne holčička babičku.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/objima_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady holčička objímá dědečka, ne babičku.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/objima_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady objímá kluk, ne holčička.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/objima_lexb_why.mp3'),
  },
  {
    id: 'budi',
    field: 'field51',
    sentence: 'Tatínka budí holčička.',
    audio: require('../assets/audio/budi.mp3'),
    targetImage: require('../assets/images/budi_target.png'),
    grammaticalDistractorImage: require('../assets/images/budi_gram.png'),
    lexicalDistractorAImage: require('../assets/images/budi_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/budi_lexb.png'),
    grammaticalDistractorExplanation: 'Tady budí tatínek holčičku, ne holčička tatínka.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/budi_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady holčička budí dědečka, ne tatínka.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/budi_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady budí maminka, ne holčička.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/budi_lexb_why.mp3'),
  },
  {
    id: 'krmi',
    field: 'field51',
    sentence: 'Dědečka krmí babička.',
    audio: require('../assets/audio/krmi.mp3'),
    targetImage: require('../assets/images/krmi_target.png'),
    grammaticalDistractorImage: require('../assets/images/krmi_gram.png'),
    lexicalDistractorAImage: require('../assets/images/krmi_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/krmi_lexb.png'),
    grammaticalDistractorExplanation: 'Tady krmí dědeček babičku, ne babička dědečka.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/krmi_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady babička krmí miminko, ne dědečka.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/krmi_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady krmí holčička, ne babička.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/krmi_lexb_why.mp3'),
  },
  {
    id: 'kresli',
    field: 'field51',
    sentence: 'Kluka kreslí holčička.',
    audio: require('../assets/audio/kresli.mp3'),
    targetImage: require('../assets/images/kresli_target.png'),
    grammaticalDistractorImage: require('../assets/images/kresli_gram.png'),
    lexicalDistractorAImage: require('../assets/images/kresli_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/kresli_lexb.png'),
    grammaticalDistractorExplanation: 'Tady kreslí kluk holčičku, ne holčička kluka.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/kresli_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady holčička kreslí pejska, ne kluka.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/kresli_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady kreslí babička, ne holčička.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/kresli_lexb_why.mp3'),
  },
  {
    id: 'tahne',
    field: 'field51',
    sentence: 'Kluka táhne holčička.',
    audio: require('../assets/audio/tahne.mp3'),
    targetImage: require('../assets/images/tahne_target.png'),
    grammaticalDistractorImage: require('../assets/images/tahne_gram.png'),
    lexicalDistractorAImage: require('../assets/images/tahne_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/tahne_lexb.png'),
    grammaticalDistractorExplanation: 'Tady táhne kluk holčičku, ne holčička kluka.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/tahne_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady holčička táhne vozík, ne kluka.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/tahne_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady táhne maminka, ne holčička.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/tahne_lexb_why.mp3'),
  },
  {
    id: 'hladi',
    field: 'field51',
    sentence: 'Holčičku hladí babička.',
    audio: require('../assets/audio/hladi.mp3'),
    targetImage: require('../assets/images/hladi_target.png'),
    grammaticalDistractorImage: require('../assets/images/hladi_gram.png'),
    lexicalDistractorAImage: require('../assets/images/hladi_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/hladi_lexb.png'),
    grammaticalDistractorExplanation: 'Tady hladí holčička babičku, ne babička holčičku.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/hladi_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady babička hladí kočku, ne holčičku.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/hladi_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady hladí maminka, ne babička.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/hladi_lexb_why.mp3'),
  },
  // Field 5.2 — Předložkové vazby a prostorové vztahy (content spec items 1-20).
  {
    id: 'podzidli',
    field: 'field52',
    sentence: 'Míč leží pod židlí.',
    audio: require('../assets/audio/podzidli.mp3'),
    targetImage: require('../assets/images/podzidli_target.png'),
    grammaticalDistractorImage: require('../assets/images/podzidli_gram.png'),
    lexicalDistractorAImage: require('../assets/images/podzidli_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/podzidli_lexb.png'),
    grammaticalDistractorExplanation: 'Tady je míč na židli, ne pod židlí.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/podzidli_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady je pod židlí kostka, ne míč.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/podzidli_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady je míč pod stolem, ne pod židlí.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/podzidli_lexb_why.mp3'),
  },
  {
    id: 'podpolstar',
    field: 'field52',
    sentence: 'Medvídek schoval kostku pod polštář.',
    audio: require('../assets/audio/podpolstar.mp3'),
    targetImage: require('../assets/images/podpolstar_target.png'),
    grammaticalDistractorImage: require('../assets/images/podpolstar_gram.png'),
    lexicalDistractorAImage: require('../assets/images/podpolstar_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/podpolstar_lexb.png'),
    grammaticalDistractorExplanation: 'Tady je kostka na polštáři, ne pod polštářem.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/podpolstar_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady je pod polštářem autíčko, ne kostka.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/podpolstar_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady schovává kostku králík, ne medvídek.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/podpolstar_lexb_why.mp3'),
  },
  {
    id: 'poddestnikem',
    field: 'field52',
    sentence: 'Kočka sedí pod deštníkem.',
    audio: require('../assets/audio/poddestnikem.mp3'),
    targetImage: require('../assets/images/poddestnikem_target.png'),
    grammaticalDistractorImage: require('../assets/images/poddestnikem_gram.png'),
    lexicalDistractorAImage: require('../assets/images/poddestnikem_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/poddestnikem_lexb.png'),
    grammaticalDistractorExplanation: 'Tady je kočka na deštníku, ne pod deštníkem.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/poddestnikem_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady sedí pod deštníkem pes, ne kočka.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/poddestnikem_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady kočka sedí pod židlí, ne pod deštníkem.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/poddestnikem_lexb_why.mp3'),
  },
  {
    id: 'vevane',
    field: 'field52',
    sentence: 'Kočka sedí ve vaně.',
    audio: require('../assets/audio/vevane.mp3'),
    targetImage: require('../assets/images/vevane_target.png'),
    grammaticalDistractorImage: require('../assets/images/vevane_gram.png'),
    lexicalDistractorAImage: require('../assets/images/vevane_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/vevane_lexb.png'),
    grammaticalDistractorExplanation: 'Tady kočka sedí vedle vany, ne ve vaně.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/vevane_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady je ve vaně pes, ne kočka.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/vevane_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady kočka sedí v krabici, ne ve vaně.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/vevane_lexb_why.mp3'),
  },
  {
    id: 'vbote',
    field: 'field52',
    sentence: 'Klíč je v botě.',
    audio: require('../assets/audio/vbote.mp3'),
    targetImage: require('../assets/images/vbote_target.png'),
    grammaticalDistractorImage: require('../assets/images/vbote_gram.png'),
    lexicalDistractorAImage: require('../assets/images/vbote_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/vbote_lexb.png'),
    grammaticalDistractorExplanation: 'Tady je klíč vedle boty, ne v botě.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/vbote_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady je v botě penízek, ne klíč.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/vbote_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady je klíč v hrnku, ne v botě.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/vbote_lexb_why.mp3'),
  },
  {
    id: 'nastole',
    field: 'field52',
    sentence: 'Bota leží na stole.',
    audio: require('../assets/audio/nastole.mp3'),
    targetImage: require('../assets/images/nastole_target.png'),
    grammaticalDistractorImage: require('../assets/images/nastole_gram.png'),
    lexicalDistractorAImage: require('../assets/images/nastole_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/nastole_lexb.png'),
    grammaticalDistractorExplanation: 'Tady je bota pod stolem, ne na stole.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/nastole_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady je na stole čepice, ne bota.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/nastole_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady bota leží na židli, ne na stole.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/nastole_lexb_why.mp3'),
  },
  {
    id: 'zaplotem',
    field: 'field52',
    sentence: 'Chlapec stojí za plotem.',
    audio: require('../assets/audio/zaplotem.mp3'),
    targetImage: require('../assets/images/zaplotem_target.png'),
    grammaticalDistractorImage: require('../assets/images/zaplotem_gram.png'),
    lexicalDistractorAImage: require('../assets/images/zaplotem_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/zaplotem_lexb.png'),
    grammaticalDistractorExplanation: 'Tady chlapec stojí před plotem, ne za plotem.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/zaplotem_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady je za plotem pes, ne chlapec.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/zaplotem_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady chlapec sedí na plotě, nestojí za ním.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/zaplotem_lexb_why.mp3'),
  },
  {
    id: 'zavazou',
    field: 'field52',
    sentence: 'Kočka sedí za vázou.',
    audio: require('../assets/audio/zavazou.mp3'),
    targetImage: require('../assets/images/zavazou_target.png'),
    grammaticalDistractorImage: require('../assets/images/zavazou_gram.png'),
    lexicalDistractorAImage: require('../assets/images/zavazou_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/zavazou_lexb.png'),
    grammaticalDistractorExplanation: 'Tady kočka sedí před vázou, ne za vázou.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/zavazou_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady je za vázou králík, ne kočka.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/zavazou_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady kočka sedí za krabicí, ne za vázou.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/zavazou_lexb_why.mp3'),
  },
  {
    id: 'zastromem',
    field: 'field52',
    sentence: 'Kluk stojí za stromem.',
    audio: require('../assets/audio/zastromem.mp3'),
    targetImage: require('../assets/images/zastromem_target.png'),
    grammaticalDistractorImage: require('../assets/images/zastromem_gram.png'),
    lexicalDistractorAImage: require('../assets/images/zastromem_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/zastromem_lexb.png'),
    grammaticalDistractorExplanation: 'Tady kluk stojí před stromem, ne za stromem.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/zastromem_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady za stromem stojí holčička, ne kluk.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/zastromem_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady kluk stojí za krabicí, ne za stromem.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/zastromem_lexb_why.mp3'),
  },
  {
    id: 'prede',
    field: 'field52',
    sentence: 'Míč leží před dveřmi.',
    audio: require('../assets/audio/prede.mp3'),
    targetImage: require('../assets/images/prede_target.png'),
    grammaticalDistractorImage: require('../assets/images/prede_gram.png'),
    lexicalDistractorAImage: require('../assets/images/prede_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/prede_lexb.png'),
    grammaticalDistractorExplanation: 'Tady je míč za dveřmi, ne před dveřmi.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/prede_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady je přede dveřmi bota, ne míč.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/prede_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady míč leží před skříní, ne přede dveřmi.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/prede_lexb_why.mp3'),
  },
  {
    id: 'vedlekosiku',
    field: 'field52',
    sentence: 'Jablko spadlo vedle košíku.',
    audio: require('../assets/audio/vedlekosiku.mp3'),
    targetImage: require('../assets/images/vedlekosiku_target.png'),
    grammaticalDistractorImage: require('../assets/images/vedlekosiku_gram.png'),
    lexicalDistractorAImage: require('../assets/images/vedlekosiku_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/vedlekosiku_lexb.png'),
    grammaticalDistractorExplanation: 'Tady je jablko v košíku, ne vedle košíku.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/vedlekosiku_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady je vedle košíku hruška, ne jablko.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/vedlekosiku_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady jablko visí nad košíkem, nespadlo vedle něj.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/vedlekosiku_lexb_why.mp3'),
  },
  {
    id: 'mezivazou',
    field: 'field52',
    sentence: 'Míč leží mezi vázou a knížkou.',
    audio: require('../assets/audio/mezivazou.mp3'),
    targetImage: require('../assets/images/mezivazou_target.png'),
    grammaticalDistractorImage: require('../assets/images/mezivazou_gram.png'),
    lexicalDistractorAImage: require('../assets/images/mezivazou_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/mezivazou_lexb.png'),
    grammaticalDistractorExplanation: 'Tady je uprostřed váza, ne míč.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/mezivazou_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady mezi vázou a knížkou leží kostka, ne míč.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/mezivazou_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady je vedle míče hrnek, ne knížka.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/mezivazou_lexb_why.mp3'),
  },
  {
    id: 'mezirodici',
    field: 'field52',
    sentence: 'Maminka stojí mezi klukem a tatínkem.',
    audio: require('../assets/audio/mezirodici.mp3'),
    targetImage: require('../assets/images/mezirodici_target.png'),
    grammaticalDistractorImage: require('../assets/images/mezirodici_gram.png'),
    lexicalDistractorAImage: require('../assets/images/mezirodici_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/mezirodici_lexb.png'),
    grammaticalDistractorExplanation: 'Tady stojí uprostřed kluk, ne maminka.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/mezirodici_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady stojí uprostřed babička, ne maminka.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/mezirodici_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady maminka stojí mezi klukem a dědečkem, ne tatínkem.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/mezirodici_lexb_why.mp3'),
  },
  {
    id: 'nastul',
    field: 'field52',
    sentence: 'Kočka skáče na stůl.',
    audio: require('../assets/audio/nastul.mp3'),
    targetImage: require('../assets/images/nastul_target.png'),
    grammaticalDistractorImage: require('../assets/images/nastul_gram.png'),
    lexicalDistractorAImage: require('../assets/images/nastul_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/nastul_lexb.png'),
    grammaticalDistractorExplanation: 'Tady kočka skáče ze stolu dolů, ne na stůl.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/nastul_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady skáče na stůl pes, ne kočka.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/nastul_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady kočka skáče na postel, ne na stůl.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/nastul_lexb_why.mp3'),
  },
  {
    id: 'preskrabici',
    field: 'field52',
    sentence: 'Pes skáče přes krabici.',
    audio: require('../assets/audio/preskrabici.mp3'),
    targetImage: require('../assets/images/preskrabici_target.png'),
    grammaticalDistractorImage: require('../assets/images/preskrabici_gram.png'),
    lexicalDistractorAImage: require('../assets/images/preskrabici_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/preskrabici_lexb.png'),
    grammaticalDistractorExplanation: 'Tady pes skáče do krabice, ne přes krabici.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/preskrabici_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady skáče přes krabici kočka, ne pes.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/preskrabici_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady pes leží za krabicí, neskáče přes ni.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/preskrabici_lexb_why.mp3'),
  },
  {
    id: 'skrz',
    field: 'field52',
    sentence: 'Kočka leze skrz plot.',
    audio: require('../assets/audio/skrz.mp3'),
    targetImage: require('../assets/images/skrz_target.png'),
    grammaticalDistractorImage: require('../assets/images/skrz_gram.png'),
    lexicalDistractorAImage: require('../assets/images/skrz_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/skrz_lexb.png'),
    grammaticalDistractorExplanation: 'Tady kočka leze přes plot nahoře, ne skrz plot.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/skrz_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady leze skrz plot pes, ne kočka.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/skrz_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady kočka leze skrz rouru, ne skrz plot.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/skrz_lexb_why.mp3'),
  },
  {
    id: 'kolem',
    field: 'field52',
    sentence: 'Kluk běží kolem stromu.',
    audio: require('../assets/audio/kolem.mp3'),
    targetImage: require('../assets/images/kolem_target.png'),
    grammaticalDistractorImage: require('../assets/images/kolem_gram.png'),
    lexicalDistractorAImage: require('../assets/images/kolem_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/kolem_lexb.png'),
    grammaticalDistractorExplanation: 'Tady kluk běží ke stromu, ne kolem stromu.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/kolem_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady běží kolem stromu holčička, ne kluk.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/kolem_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady kluk běží kolem domu, ne kolem stromu.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/kolem_lexb_why.mp3'),
  },
  {
    id: 'dokose',
    field: 'field52',
    sentence: 'Kluk hází míč do koše.',
    audio: require('../assets/audio/dokose.mp3'),
    targetImage: require('../assets/images/dokose_target.png'),
    grammaticalDistractorImage: require('../assets/images/dokose_gram.png'),
    lexicalDistractorAImage: require('../assets/images/dokose_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/dokose_lexb.png'),
    grammaticalDistractorExplanation: 'Tady míč letí přes koš, ne do koše.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/dokose_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady kluk hází do koše kostku, ne míč.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/dokose_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady hází míč holčička, ne kluk.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/dokose_lexb_why.mp3'),
  },
  {
    id: 'zkrabice',
    field: 'field52',
    sentence: 'Ptáček letí z krabice.',
    audio: require('../assets/audio/zkrabice.mp3'),
    targetImage: require('../assets/images/zkrabice_target.png'),
    grammaticalDistractorImage: require('../assets/images/zkrabice_gram.png'),
    lexicalDistractorAImage: require('../assets/images/zkrabice_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/zkrabice_lexb.png'),
    grammaticalDistractorExplanation: 'Tady ptáček letí do krabice, ne z krabice.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/zkrabice_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady letí z krabice motýl, ne ptáček.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/zkrabice_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady ptáček sedí na krabici, neletí z ní.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/zkrabice_lexb_why.mp3'),
  },
  {
    id: 'nadstrechou',
    field: 'field52',
    sentence: 'Ptáček letí nad střechou.',
    audio: require('../assets/audio/nadstrechou.mp3'),
    targetImage: require('../assets/images/nadstrechou_target.png'),
    grammaticalDistractorImage: require('../assets/images/nadstrechou_gram.png'),
    lexicalDistractorAImage: require('../assets/images/nadstrechou_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/nadstrechou_lexb.png'),
    grammaticalDistractorExplanation: 'Tady ptáček letí pod střechou, ne nad střechou.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/nadstrechou_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady letí nad střechou letadlo, ne ptáček.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/nadstrechou_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady ptáček letí nad stromem, ne nad střechou.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/nadstrechou_lexb_why.mp3'),
  },
  // Field 5.3 — Gramatické číslo: singulár vs. plurál (content spec items 1-20).
  {
    id: 'hrusky',
    field: 'field53',
    sentence: 'Hrušky leží na talíři.',
    audio: require('../assets/audio/hrusky.mp3'),
    targetImage: require('../assets/images/hrusky_target.png'),
    grammaticalDistractorImage: require('../assets/images/hrusky_gram.png'),
    lexicalDistractorAImage: require('../assets/images/hrusky_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/hrusky_lexb.png'),
    grammaticalDistractorExplanation: 'Tady je jen jedna hruška, ne víc hrušek.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/hrusky_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady jsou na talíři jablka, ne hrušky.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/hrusky_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady hrušky leží pod stolem, ne na talíři.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/hrusky_lexb_why.mp3'),
  },
  {
    id: 'svihadlo',
    field: 'field53',
    sentence: 'Kluk skáče přes švihadlo.',
    audio: require('../assets/audio/svihadlo.mp3'),
    targetImage: require('../assets/images/svihadlo_target.png'),
    grammaticalDistractorImage: require('../assets/images/svihadlo_gram.png'),
    lexicalDistractorAImage: require('../assets/images/svihadlo_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/svihadlo_lexb.png'),
    grammaticalDistractorExplanation: 'Tady skáčou tři kluci, ne jeden kluk.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/svihadlo_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady skáče holčička, ne kluk.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/svihadlo_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady kluk skáče přes lavičku, ne přes švihadlo.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/svihadlo_lexb_why.mp3'),
  },
  {
    id: 'kockypiji',
    field: 'field53',
    sentence: 'Kočky pijí z misky.',
    audio: require('../assets/audio/kockypiji.mp3'),
    targetImage: require('../assets/images/kockypiji_target.png'),
    grammaticalDistractorImage: require('../assets/images/kockypiji_gram.png'),
    lexicalDistractorAImage: require('../assets/images/kockypiji_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/kockypiji_lexb.png'),
    grammaticalDistractorExplanation: 'Tady pije jen jedna kočka, ne víc koček.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/kockypiji_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady pijí z misky psi, ne kočky.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/kockypiji_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady kočky spí, nepijí z misky.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/kockypiji_lexb_why.mp3'),
  },
  {
    id: 'okna',
    field: 'field53',
    sentence: 'Okna jsou otevřená.',
    audio: require('../assets/audio/okna.mp3'),
    targetImage: require('../assets/images/okna_target.png'),
    grammaticalDistractorImage: require('../assets/images/okna_gram.png'),
    lexicalDistractorAImage: require('../assets/images/okna_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/okna_lexb.png'),
    grammaticalDistractorExplanation: 'Tady je otevřené jen jedno okno, ne všechna.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/okna_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady jsou otevřené dveře, ne okna.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/okna_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady jsou okna zavřená, ne otevřená.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/okna_lexb_why.mp3'),
  },
  {
    id: 'medvidci',
    field: 'field53',
    sentence: 'Medvídci sedí na posteli.',
    audio: require('../assets/audio/medvidci.mp3'),
    targetImage: require('../assets/images/medvidci_target.png'),
    grammaticalDistractorImage: require('../assets/images/medvidci_gram.png'),
    lexicalDistractorAImage: require('../assets/images/medvidci_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/medvidci_lexb.png'),
    grammaticalDistractorExplanation: 'Tady sedí jen jeden medvídek, ne víc medvídků.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/medvidci_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady sedí na posteli králíčci, ne medvídci.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/medvidci_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady medvídci sedí na židli, ne na posteli.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/medvidci_lexb_why.mp3'),
  },
  {
    id: 'klukstavi',
    field: 'field53',
    sentence: 'Kluk staví kostky.',
    audio: require('../assets/audio/klukstavi.mp3'),
    targetImage: require('../assets/images/klukstavi_target.png'),
    grammaticalDistractorImage: require('../assets/images/klukstavi_gram.png'),
    lexicalDistractorAImage: require('../assets/images/klukstavi_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/klukstavi_lexb.png'),
    grammaticalDistractorExplanation: 'Tady staví kostky tři kluci, ne jeden kluk.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/klukstavi_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady staví kostky holčička, ne kluk.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/klukstavi_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady kluk staví knížky, ne kostky.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/klukstavi_lexb_why.mp3'),
  },
  {
    id: 'ptaci',
    field: 'field53',
    sentence: 'Ptáci sedí na větvi.',
    audio: require('../assets/audio/ptaci.mp3'),
    targetImage: require('../assets/images/ptaci_target.png'),
    grammaticalDistractorImage: require('../assets/images/ptaci_gram.png'),
    lexicalDistractorAImage: require('../assets/images/ptaci_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/ptaci_lexb.png'),
    grammaticalDistractorExplanation: 'Tady sedí jen jeden pták, ne víc ptáků.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/ptaci_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady sedí na větvi veverky, ne ptáci.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/ptaci_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady ptáci létají, nesedí na větvi.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/ptaci_lexb_why.mp3'),
  },
  {
    id: 'psispi',
    field: 'field53',
    sentence: 'Psi spí na koberci.',
    audio: require('../assets/audio/psispi.mp3'),
    targetImage: require('../assets/images/psispi_target.png'),
    grammaticalDistractorImage: require('../assets/images/psispi_gram.png'),
    lexicalDistractorAImage: require('../assets/images/psispi_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/psispi_lexb.png'),
    grammaticalDistractorExplanation: 'Tady spí jen jeden pes, ne víc psů.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/psispi_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady spí na koberci kočky, ne psi.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/psispi_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady si psi hrají, nespí.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/psispi_lexb_why.mp3'),
  },
  {
    id: 'lavicka',
    field: 'field53',
    sentence: 'Kluk sedí na lavičce.',
    audio: require('../assets/audio/lavicka.mp3'),
    targetImage: require('../assets/images/lavicka_target.png'),
    grammaticalDistractorImage: require('../assets/images/lavicka_gram.png'),
    lexicalDistractorAImage: require('../assets/images/lavicka_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/lavicka_lexb.png'),
    grammaticalDistractorExplanation: 'Tady sedí tři kluci, ne jeden kluk.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/lavicka_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady sedí na lavičce holčička, ne kluk.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/lavicka_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady kluk na lavičce leží, nesedí.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/lavicka_lexb_why.mp3'),
  },
  {
    id: 'kvetiny',
    field: 'field53',
    sentence: 'Květiny jsou ve váze.',
    audio: require('../assets/audio/kvetiny.mp3'),
    targetImage: require('../assets/images/kvetiny_target.png'),
    grammaticalDistractorImage: require('../assets/images/kvetiny_gram.png'),
    lexicalDistractorAImage: require('../assets/images/kvetiny_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/kvetiny_lexb.png'),
    grammaticalDistractorExplanation: 'Tady je ve váze jen jedna květina, ne víc květin.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/kvetiny_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady jsou ve váze větvičky, ne květiny.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/kvetiny_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady květiny leží vedle vázy, nejsou ve váze.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/kvetiny_lexb_why.mp3'),
  },
  {
    id: 'hrnek',
    field: 'field53',
    sentence: 'Hrnek stojí na stole.',
    audio: require('../assets/audio/hrnek.mp3'),
    targetImage: require('../assets/images/hrnek_target.png'),
    grammaticalDistractorImage: require('../assets/images/hrnek_gram.png'),
    lexicalDistractorAImage: require('../assets/images/hrnek_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/hrnek_lexb.png'),
    grammaticalDistractorExplanation: 'Tady stojí tři hrnky, ne jeden hrnek.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/hrnek_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady stojí na stole sklenice, ne hrnek.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/hrnek_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady je hrnek pod stolem, ne na stole.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/hrnek_lexb_why.mp3'),
  },
  {
    id: 'kone',
    field: 'field53',
    sentence: 'Koně běží.',
    audio: require('../assets/audio/kone.mp3'),
    targetImage: require('../assets/images/kone_target.png'),
    grammaticalDistractorImage: require('../assets/images/kone_gram.png'),
    lexicalDistractorAImage: require('../assets/images/kone_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/kone_lexb.png'),
    grammaticalDistractorExplanation: 'Tady běží jen jeden kůň, ne víc koní.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/kone_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady běží krávy, ne koně.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/kone_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady koně jenom stojí, vůbec neběží.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/kone_lexb_why.mp3'),
  },
  {
    id: 'jablko',
    field: 'field53',
    sentence: 'Jablko leží v košíku.',
    audio: require('../assets/audio/jablko.mp3'),
    targetImage: require('../assets/images/jablko_target.png'),
    grammaticalDistractorImage: require('../assets/images/jablko_gram.png'),
    lexicalDistractorAImage: require('../assets/images/jablko_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/jablko_lexb.png'),
    grammaticalDistractorExplanation: 'Tady jsou v košíku tři jablka, ne jedno jablko.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/jablko_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady je v košíku hruška, ne jablko.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/jablko_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady jablko leží vedle košíku, ne v košíku.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/jablko_lexb_why.mp3'),
  },
  {
    id: 'deti',
    field: 'field53',
    sentence: 'Děti si hrají v pískovišti.',
    audio: require('../assets/audio/deti.mp3'),
    targetImage: require('../assets/images/deti_target.png'),
    grammaticalDistractorImage: require('../assets/images/deti_gram.png'),
    lexicalDistractorAImage: require('../assets/images/deti_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/deti_lexb.png'),
    grammaticalDistractorExplanation: 'Tady si hraje jen jedno dítě, ne víc dětí.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/deti_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady si v pískovišti hrají pejsci, ne děti.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/deti_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady děti spí, nehrají si.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/deti_lexb_why.mp3'),
  },
  {
    id: 'svicka',
    field: 'field53',
    sentence: 'Svíčka hoří na dortu.',
    audio: require('../assets/audio/svicka.mp3'),
    targetImage: require('../assets/images/svicka_target.png'),
    grammaticalDistractorImage: require('../assets/images/svicka_gram.png'),
    lexicalDistractorAImage: require('../assets/images/svicka_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/svicka_lexb.png'),
    grammaticalDistractorExplanation: 'Tady hoří tři svíčky, ne jedna svíčka.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/svicka_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady na dortu hoří prskavka, ne svíčka.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/svicka_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady svíčka nehoří, nemá plamínek.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/svicka_lexb_why.mp3'),
  },
  {
    id: 'ryby',
    field: 'field53',
    sentence: 'Ryby plavou v akváriu.',
    audio: require('../assets/audio/ryby.mp3'),
    targetImage: require('../assets/images/ryby_target.png'),
    grammaticalDistractorImage: require('../assets/images/ryby_gram.png'),
    lexicalDistractorAImage: require('../assets/images/ryby_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/ryby_lexb.png'),
    grammaticalDistractorExplanation: 'Tady plave jen jedna ryba, ne víc ryb.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/ryby_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady plavou v akváriu želvy, ne ryby.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/ryby_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady ryby plavou ve vaně, ne v akváriu.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/ryby_lexb_why.mp3'),
  },
  {
    id: 'kniha',
    field: 'field53',
    sentence: 'Kniha leží na polici.',
    audio: require('../assets/audio/kniha.mp3'),
    targetImage: require('../assets/images/kniha_target.png'),
    grammaticalDistractorImage: require('../assets/images/kniha_gram.png'),
    lexicalDistractorAImage: require('../assets/images/kniha_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/kniha_lexb.png'),
    grammaticalDistractorExplanation: 'Tady leží tři knihy, ne jedna kniha.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/kniha_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady je na polici autíčko, ne kniha.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/kniha_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady kniha leží na stole, ne na polici.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/kniha_lexb_why.mp3'),
  },
  {
    id: 'banany',
    field: 'field53',
    sentence: 'Banány leží v misce.',
    audio: require('../assets/audio/banany.mp3'),
    targetImage: require('../assets/images/banany_target.png'),
    grammaticalDistractorImage: require('../assets/images/banany_gram.png'),
    lexicalDistractorAImage: require('../assets/images/banany_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/banany_lexb.png'),
    grammaticalDistractorExplanation: 'Tady je v misce jen jeden banán, ne víc banánů.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/banany_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady jsou v misce jablka, ne banány.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/banany_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady banány leží vedle misky, ne v misce.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/banany_lexb_why.mp3'),
  },
  {
    id: 'zaba',
    field: 'field53',
    sentence: 'Žába sedí na kameni.',
    audio: require('../assets/audio/zaba.mp3'),
    targetImage: require('../assets/images/zaba_target.png'),
    grammaticalDistractorImage: require('../assets/images/zaba_gram.png'),
    lexicalDistractorAImage: require('../assets/images/zaba_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/zaba_lexb.png'),
    grammaticalDistractorExplanation: 'Tady sedí tři žáby, ne jedna žába.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/zaba_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady sedí na kameni kachna, ne žába.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/zaba_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady žába skáče, nesedí na kameni.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/zaba_lexb_why.mp3'),
  },
  {
    id: 'tancuje',
    field: 'field53',
    sentence: 'Holčička tancuje.',
    audio: require('../assets/audio/tancuje.mp3'),
    targetImage: require('../assets/images/tancuje_target.png'),
    grammaticalDistractorImage: require('../assets/images/tancuje_gram.png'),
    lexicalDistractorAImage: require('../assets/images/tancuje_lexa.png'),
    lexicalDistractorBImage: require('../assets/images/tancuje_lexb.png'),
    grammaticalDistractorExplanation: 'Tady tancují tři holčičky, ne jedna holčička.',
    grammaticalDistractorExplanationAudio: require('../assets/audio/tancuje_gram_why.mp3'),
    lexicalDistractorAExplanation: 'Tady tancuje kluk, ne holčička.',
    lexicalDistractorAExplanationAudio: require('../assets/audio/tancuje_lexa_why.mp3'),
    lexicalDistractorBExplanation: 'Tady holčička sedí na židli, netancuje.',
    lexicalDistractorBExplanationAudio: require('../assets/audio/tancuje_lexb_why.mp3'),
  },
];
